extends SceneTree
var failures=0
func check(ok:bool,message:String):
	print(("PASS: " if ok else "FAIL: ")+message)
	if not ok:failures+=1
func _init():call_deferred("run")
func run():
	var scene=load("res://original_campaign.tscn").instantiate()
	check(scene.initialize(4,0,false,5).is_empty(),"initialize dual-player ending interface")
	root.add_child(scene)
	current_scene=scene
	scene.set_process(false)
	await process_frame
	check(scene.native.load_session("res://tests/natural-dual-first-defeat.json").is_empty(),"load natural first-player defeat")
	scene.refresh()
	scene.show_battle_details()
	check(scene.human_failure_controls.visible and not scene.human_failure_next.disabled,"first defeated human can continue with surviving player")
	check(not scene.ending_report.visible and not scene.ending_button.visible,"first human failure is not the campaign ending")
	scene.deployment_action("human_failure_next")
	check(not scene.state.battle.tactics.has("human_failure") and scene.state.phase!="ending","failure confirmation resumes settlement")
	scene.battle_details.hide()
	check(scene.native.load_session("res://tests/natural-dual-before-year-limit.json").is_empty(),"restore natural final month")
	scene.refresh()
	check(scene.state.year==249 and scene.state.month==12,"natural checkpoint is249/12")
	if scene.state.phase=="player_commands":scene.end_turn()
	else:scene.advance_ai()
	check(scene.state.phase=="ending" and scene.state.ending.kind=="year_limit","monthly transition enters year-limit ending")
	check(scene.state.year==250 and scene.state.month==1,"year-limit date is250/1")
	check(scene.ending_report.visible and scene.ending_button.visible and scene.ending_report.dialog_text.contains("仍未统一天下"),"terminal report opens with correct outcome")
	for button in [scene.end_button,scene.develop_button,scene.move_button,scene.search_button,scene.recruit_button,scene.orders_button,scene.expedition_button]:
		check(button.disabled,"terminal gameplay command disabled: "+button.text)
	var before:Dictionary=scene.native.session_snapshot()
	scene._process(1.0)
	check(scene.native.session_snapshot()==before,"terminal display no longer advances native frame clock")
	check(not scene.native.end_turn().is_empty(),"terminal end-turn rejected")
	scene.native.advance_turn()
	check(scene.native.session_snapshot()==before,"terminal strategic advance preserves entire state")
	scene.ending_report.hide()
	scene.refresh()
	check(not scene.ending_report.visible,"map inspection does not repeatedly reopen report")
	scene.ending_button.pressed.emit()
	check(scene.ending_report.visible,"terminal report can be reopened")
	# Preserve an existing user save while exercising the actual save/load UI.
	var path:String=ProjectSettings.globalize_path(scene.SAVE)
	var existed:bool=FileAccess.file_exists(path)
	var original:PackedByteArray=FileAccess.get_file_as_bytes(path) if existed else PackedByteArray()
	scene.save_game()
	scene.ending_report.hide()
	scene.load_game()
	check(scene.ending_report.visible and scene.native.session_snapshot()==before,"save/load restores complete ending and reopens report")
	if existed:
		var file=FileAccess.open(path,FileAccess.WRITE)
		file.store_buffer(original)
		file.close()
	else:DirAccess.remove_absolute(path)
	check(scene.native.load_session("res://tests/natural-dual-first-defeat.json").is_empty(),"load earlier battle after terminal state")
	scene.refresh()
	check(not scene.ending_report.visible and not scene.ending_button.visible,"earlier save clears stale terminal controls")
	scene.show_battle_details()
	check(scene.battle_details.visible,"earlier battle report is open before terminal load")
	check(scene.native.load_session("res://tests/natural-dual-year-limit.json").is_empty(),"restore final ending fixture")
	scene.refresh()
	check(not scene.battle_details.visible,"terminal restore hides stale battle report")
	scene.ending_report.custom_action.emit(&"title")
	await process_frame
	await process_frame
	check(current_scene!=scene and current_scene.scene_file_path=="res://opening.tscn","ending report returns to title")
	await root.get_node("OriginalSound").shutdown()
	print("ORIGINAL CAMPAIGN ENDING: %d failures" % failures)
	quit(1 if failures else 0)
