extends SceneTree
var failures=0
var scene:Control
var path="user://native-computer-role-test.json"
func check(ok:bool,message:String):
	print(("PASS: " if ok else "FAIL: ")+message)
	if not ok:failures+=1
func reload_step():
	var before:Dictionary=scene.native.session_snapshot()
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot()==before,"role continuation reloads exactly")
func _init():call_deferred("run")
func run():
	scene=load("res://original_campaign.tscn").instantiate()
	check(scene.initialize(4,2).is_empty(),"initialize role-return continuation")
	root.add_child(scene)
	scene.set_process(false)
	await process_frame
	check(scene.native.load_session("res://tests/computer-role-start.json").is_empty(),"load legal movement, retreat and role-update history")
	scene.refresh()
	scene.show_battle_details()
	var before:Dictionary=scene.native.session_snapshot()
	check(int(before.battle.tactics.computer.role_slot)==5 and int(before.battle.tactics.computer_cursor)==5,"role update retains original scan slot")
	check(not scene.native.plan_computer_tactics().is_empty() and scene.native.session_snapshot()==before,"legacy planning cannot skip the residual command")
	check(scene.computer_next.visible and not scene.computer_next.disabled and scene.computer_next.text=="继续角色调整后的行动","UI exposes verified role continuation")
	reload_step()
	scene.computer_next.emit_signal("pressed")
	var after:Dictionary=scene.native.session_snapshot()
	check(after.battle.tactics.computer_motion.kind=="move" and int(after.battle.tactics.points)==26 and int(after.sram[0xdab])==83,"button executes inherited left movement with exact mobility")
	check(int(after.battle.tactics.computer_cursor)==5 and int(after.battle.tactics.selected)==0 and after.battle.tactics.moves[-1].kind=="computer_role_return","command slot and scan cursor remain distinct")
	reload_step()
	check(not scene.native.continue_computer_role().is_empty() and scene.native.session_snapshot()==after,"no repeated role movement")
	scene.computer_next.emit_signal("pressed")
	scene.computer_next.emit_signal("pressed")
	check(int(scene.state.battle.tactics.computer_plan.slot)==3,"next decision skips the departed slot four")
	reload_step()
	check(scene.native.load_session("res://tests/computer-role-blocked.json").is_empty(),"load legal blocked-command history")
	scene.refresh()
	scene.show_battle_details()
	before=scene.native.session_snapshot()
	check(not scene.computer_next.disabled,"blocked movement can return to assessment")
	scene.computer_next.emit_signal("pressed")
	after=scene.native.session_snapshot()
	check(after.battle.tactics.computer_motion.kind=="blocked" and int(after.battle.tactics.points)==29 and after.sram==before.sram,"blocked command preserves SRAM and mobility")
	reload_step()
	scene.computer_next.emit_signal("pressed")
	scene.computer_next.emit_signal("pressed")
	check(int(scene.state.battle.tactics.computer_plan.slot)==3,"blocked command continues original scan")
	check(scene.native.load_session("res://tests/computer-role-unknown.json").is_empty(),"load a different history without a known residual direction")
	scene.refresh()
	scene.show_battle_details()
	before=scene.native.session_snapshot()
	check(scene.computer_next.disabled and not scene.native.can_continue_computer_role(),"unknown direction does not inherit the previous game's value")
	check(not scene.native.continue_computer_role().is_empty() and scene.native.session_snapshot()==before,"unknown-direction rejection is atomic")
	check(scene.battle_description.text.contains("上一指令的方向尚未确定"),"held boundary explains the remaining reconstruction gap")
	scene.battle_details.hide()
	for suffix in ["","-next"]:
		check(scene.native.load_session("res://tests/natural-role-handover"+suffix+".json").is_empty(),"load naturally reached eighth-battle role boundary")
		scene.refresh();scene.show_battle_details()
		var natural:Dictionary=scene.native.session_snapshot()
		check(scene.computer_next.visible and not scene.computer_next.disabled,"verified handover direction enables the existing continuation button")
		scene.computer_next.emit_signal("pressed")
		check(scene.state.battle.tactics.computer_motion.argument==(1 if suffix.is_empty() else 2) and scene.state.random_cursor==natural.random_cursor,"button recovers original direction without drawing RNG")
		var recovered:Dictionary=scene.native.session_snapshot()
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot()==recovered,"recovered archived history reloads exactly")
		check(not scene.native.resume_computer_role_after_handover().is_empty() and scene.native.session_snapshot()==recovered,"UI binding rejects duplicate recovery")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	print("ORIGINAL COMPUTER ROLE: %d failures" % failures)
	await root.get_node("OriginalSound").shutdown()
	quit(1 if failures else 0)
