extends SceneTree
var failures = 0
func check(ok: bool, message: String):
	print(("PASS: " if ok else "FAIL: ")+message)
	if not ok: failures+=1
func _init(): call_deferred("run")
func advance_all(scene) -> void:
	for i in range(24):
		if scene.native.session_snapshot().phase!="ai_turn": break
		scene.advance_ai()

func isolated(scene, difficulty: int) -> void:
	var raw=FileAccess.get_file_as_bytes("res://reference/fixtures/initial-difficulty-%d.bin" % difficulty)
	raw[0xd89]=132
	raw[0xd8a]=0
	raw[0xd8b]=4
	raw[0xd8c]=1
	raw[0xda9]=0
	raw[0xd9f]=2 if difficulty==2 else 3
	var f=FileAccess.open("user://native-isolated-test.json",FileAccess.WRITE)
	f.store_string(JSON.stringify({"format":"native-original-v1","rom_crc32":2966394227,"sram":Array(raw),"frame_counter":0,"random_cursor":0,"pending_development":null,"pending_search":null}))
	f.close()
	check(scene.native.load_session("user://native-isolated-test.json").is_empty(),"isolated original command fixture loads")
	DirAccess.remove_absolute(ProjectSettings.globalize_path("user://native-isolated-test.json"))
	scene.select_city(13)

func run():
	var scene = load("res://original_campaign.tscn").instantiate()
	check(scene.initialize(4,2).is_empty(),"native campaign initializes from ROM")
	root.add_child(scene)
	scene.set_process(false)
	await process_frame
	isolated(scene,2)
	check(scene.state.cities.size()==30 and scene.state.officers.size()==241,"all original mutable records reach UI")
	scene.show_officers()
	check(scene.officer_list.item_count==241,"complete officer book includes every original record")
	scene.officer_book.hide()
	check(int(scene.state.rulers[4].books)==2,"hard difficulty gives Liu Bei two original books")
	check(int(scene.state.cities[13].land)==25 and int(scene.state.cities[13].population)==19000,"UI shows original fields")
	scene.prepare_development(0)
	var quote: Dictionary=scene.native.session_snapshot().pending_development
	check(int(quote.cost)==16 and scene.confirm.visible,"original proposal shown before mutation")
	check(int(scene.native.session_snapshot().cities[13].gold)==200,"quote does not spend gold")
	scene.native.tick(8)
	scene.confirm.hide()
	scene.confirm_development()
	check(int(scene.state.cities[13].gold)==184 and int(scene.state.cities[13].land)==39 and int(scene.state.cities[13].control)==58,"UI applies original development to actual records")
	scene.start_move()
	scene.select_city(21)
	check(scene.state.cities[13].officer_slots[0]==null and int(scene.state.cities[21].officer_slots[2])==4,"map interaction transfers actual selected general")
	check(int(scene.state.rulers[4].seat)==21 and int(scene.state.rulers[4].books)==0,"capital and books updated with movement")
	check(scene.develop_button.disabled and scene.move_button.disabled,"commands disable when original books run out")
	var path="user://native-session-test.json"
	check(scene.native.save_session(path).is_empty(),"native state saves through Godot binding")
	var saved: Dictionary=scene.native.session_snapshot()
	scene.native.start_session(2,0)
	check(scene.native.load_session(path).is_empty() and scene.native.session_snapshot().sram==saved.sram,"complete mutable state loads atomically")
	var f=FileAccess.open(path,FileAccess.WRITE)
	f.store_string('{"format":"native-original-v1"}')
	f.close()
	check(not scene.native.load_session(path).is_empty() and scene.native.session_snapshot().sram==saved.sram,"malformed save preserves live campaign")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	for ruler in range(6):
		check(scene.native.start_session(ruler,1).is_empty(),"native ruler %d starts" % ruler)
		advance_all(scene)
		var s:Dictionary=scene.native.session_snapshot()
		check(int(s.player)==ruler and int(s.current_ruler)==ruler and int(s.rulers[ruler].books)>0,"native ownership and books for ruler %d" % ruler)
	isolated(scene,0)
	check(scene.search_button.disabled,"ruler search is disabled")
	scene.toggle_officer(4)
	scene.toggle_officer(145)
	check(not scene.search_button.disabled,"resident non-ruler can search")
	scene.show_search()
	check(scene.search_confirm.visible,"search confirmation describes temporary absence")
	scene.search_confirm.hide()
	scene.dispatch_search()
	check(scene.state.cities[13].officer_slots[1]==null and scene.state.search_parties.size()==1,"search dispatch removes selected officer and exposes pending party")
	check(int(scene.state.rulers[4].books)==2 and scene.search_button.disabled,"search spends exactly one book and cannot empty city")
	scene.native.save_session(path)
	var fixture: Dictionary=JSON.parse_string(FileAccess.get_file_as_string(path))
	# Godot parses all JSON numbers as floats; retain the native save's integer schema.
	for i in range(fixture.sram.size()): fixture.sram[i]=int(fixture.sram[i])
	for key in ["rom_crc32","frame_counter","random_cursor"]: fixture[key]=int(fixture[key])
	fixture.sram[0xc31]=13 # Controlled return fixture; no turn/AI completion claim.
	f=FileAccess.open(path,FileAccess.WRITE)
	f.store_string(JSON.stringify(fixture))
	f.close()
	check(scene.native.load_session(path).is_empty(),"ready-return integration fixture loads")
	scene.select_city(13)
	check(scene.search_report.visible and scene.state.cities[13].officer_slots[1]!=null,"entering city restores officer and opens search report")
	var report_state: Dictionary=scene.native.session_snapshot()
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"pending search report survives native save/load")
	check(scene.native.session_snapshot().sram==report_state.sram,"report restoration cannot grant rewards twice")
	scene.search_report.hide()
	scene.finish_search(true)
	check(scene.native.session_snapshot().pending_search==null,"search report resolution clears pending state")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	scene.native.start_session(4,0)
	advance_all(scene)
	scene.select_city(13)
	check(scene.state.phase=="player_commands" and scene.state.events.size()==4,"opening AI is visible through controller")
	scene.native.search(13,145)
	scene.end_turn()
	advance_all(scene)
	check(int(scene.state.month)==2 and scene.search_report.visible,"end-turn UI advances month and shows naturally returned search report")
	scene.search_report.hide()
	scene.finish_search(true)
	isolated(scene,0)
	scene.show_recruit()
	check(scene.recruit_dialog.visible,"recruitment quote opens")
	scene.recruit_quantity.value=3
	scene.recruit_dialog.hide()
	scene.recruit()
	check(int(scene.state.cities[13].gold)==140 and int(scene.state.cities[13].reserves)==300 and int(scene.state.rulers[4].books)==2,"recruitment spends original gold and one book")
	check(scene.army_dialog.visible and scene.end_button.disabled,"recruitment opens mandatory troop assignment")
	for i in range(scene.army_officers.item_count):
		if scene.army_officers.get_item_id(i)==145:scene.army_officers.select(i);scene.select_army_officer(i)
	scene.army_quantity.value=8
	scene.assign_army()
	check(int(scene.state.cities[13].reserves)==0 and int(scene.state.officers[145].archers)==300,"recruits assigned to actual officer using original troop mix")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and int(scene.native.session_snapshot().pending_army)==13,"troop assignment phase survives save/load")
	scene.army_dialog.hide()
	scene.finish_recruitment()
	check(scene.native.session_snapshot().pending_army==null and not scene.end_button.disabled,"finishing assignment restores turn controls")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	isolated(scene,0)
	scene.order_kind.select(5)
	scene.show_orders()
	check(scene.order_dialog.visible and not scene.order_dialog.get_ok_button().disabled,"weapon shop opens for available original city service")
	scene.order_amounts[0].value=3
	scene.order_dialog.hide()
	scene.execute_order()
	check(int(scene.state.cities[13].gold)==185 and int(scene.state.cities[13].inventory[1])==3 and int(scene.state.rulers[4].books)==2,"Godot command binding buys weapons at five gold each")
	scene.order_kind.select(0)
	scene.show_orders()
	for n in range(scene.order_target.item_count):
		if scene.order_target.get_item_id(n)==21:scene.order_target.select(n)
	scene.order_amounts[0].value=10
	scene.order_amounts[1].value=2
	scene.order_dialog.hide()
	scene.execute_order()
	check(int(scene.state.cities[13].gold)==175 and int(scene.state.cities[13].inventory[1])==1 and int(scene.state.cities[21].inventory[1])==2,"transport form transfers selected quantities to neighboring friendly city")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and int(scene.native.session_snapshot().cities[21].inventory[1])==2,"new inventory commands survive full save/load")
	isolated(scene,0)
	scene.order_kind.select(9)
	scene.show_orders()
	check(scene.order_target.item_count==30,"scouting lists every original city")
	scene.order_target.select(13)
	scene.order_dialog.hide()
	scene.execute_order()
	check(scene.scout_dialog.visible and int(scene.state.rulers[4].books)==3,"scouting home terrain is free")
	check(scene.scout_texture.texture.get_width()==256 and scene.scout_texture.texture.get_height()==160,"native scouting image has original dimensions")
	scene.scout_dialog.hide()
	scene.show_orders()
	scene.order_target.select(0)
	scene.order_dialog.hide()
	scene.execute_order()
	check(int(scene.state.rulers[4].books)==2 and int(scene.state.sram[0xe1a])==7,"remote scouting spends one book and writes actual terrain cache")
	scene.scout_dialog.hide()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	isolated(scene,0)
	scene.chosen.clear()
	scene.chosen.append(145)
	scene.refresh()
	scene.show_expedition()
	check(scene.expedition_dialog.visible and not scene.expedition_dialog.get_ok_button().disabled,"expedition selection offers native quote")
	check(int(scene.native.session_snapshot().cities[13].gold)==200,"cancelable expedition quote spends nothing")
	for n in range(scene.expedition_target.item_count):
		if scene.expedition_target.get_item_id(n)==12:scene.expedition_target.select(n)
	scene.update_expedition_quote()
	scene.expedition_dialog.hide()
	scene.dispatch_expedition()
	check(scene.state.phase=="expedition" and int(scene.state.cities[13].gold)==100 and scene.state.cities[13].officer_slots[1]==null,"expedition UI transfers actual officer and original fee")
	check(scene.battle_details.visible and scene.end_button.disabled and scene.orders_button.disabled,"pending player battle blocks strategic continuation")
	check(scene.battle_attackers.item_count==1 and scene.battle_defenders.item_count==2 and int(scene.state.sram[0xdaa])==2,"original defenders and attackers reach battle roster UI")
	check(scene.state.battle.defenders==[2.0,12.0] and scene.state.cities[12].officer_slots[0]==2.0,"defender collection preserves target residents")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().phase=="expedition","player expedition survives Godot save/load")
	scene.deployment_start.emit_signal("pressed")
	check(scene.state.battle.deployment.current==0.0 and int(scene.state.sram[0xdc3])==0x2f and int(scene.state.sram[0xdab])==0x54,"original automatic defense and first attacker deployment reach UI")
	check(not scene.deployment_start.visible and not scene.deployment_confirm.disabled and scene.state.battle.deployment_area.size()==160,"deployment controls and original area are visible")
	scene.deployment_arrows[0].emit_signal("pressed")
	check(int(scene.state.sram[0xdc3])==0x2e and int(scene.state.sram[0xe48])==0x70,"left arrow moves selected unit and updates actual occupancy")
	scene.deployment_arrows[3].emit_signal("pressed")
	var border_state:Array=scene.state.sram.duplicate()
	scene.deployment_arrows[3].emit_signal("pressed")
	check(scene.state.sram==border_state and scene.battle_description.text.contains("边界"),"invalid UI move preserves deployment")
	var deployment_key=InputEventKey.new()
	deployment_key.keycode=KEY_A
	deployment_key.pressed=true
	scene.battle_details.emit_signal("window_input",deployment_key)
	check(int(scene.state.sram[0xdc3])==0x2e,"deployment window routes WASD to native movement")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().sram==scene.state.sram,"active deployment saves and restores through Godot")
	scene.battle_details.hide()
	scene.refresh()
	scene.show_battle_details()
	check(scene.battle_details.visible and scene.state.battle.deployment.current==0.0 and not scene.deployment_confirm.disabled,"closing and reopening resumes current deployment")
	scene.deployment_confirm.emit_signal("pressed")
	check(scene.state.battle.deployment.current==-1.0 and scene.deployment_confirm.disabled and scene.end_button.disabled,"final deployment confirmation pauses before unimplemented combat")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().battle.deployment.current==-1.0,"finished deployment survives Godot save/load")
	scene.battle_details.hide()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	# Restore a captured AI invasion through the public file-based session API.
	var invasion_raw=FileAccess.get_file_as_bytes("res://reference/fixtures/ai-15-after.bin")
	var ai_cases:Array=JSON.parse_string(FileAccess.get_file_as_string("res://reference/fixtures/ai.json"))
	var ai_result:Dictionary=ai_cases[15].expected
	for key in ai_result:
		if ai_result[key] is float:ai_result[key]=int(ai_result[key])
	var invasion_file=FileAccess.open(path,FileAccess.WRITE)
	invasion_file.store_string(JSON.stringify({"format":"native-original-v2","rom_crc32":2966394227,"sram":Array(invasion_raw),"frame_counter":0,"random_cursor":49,"pending_development":null,"pending_search":null,"pending_army":null,"phase":"battle","ai":ai_result,"battle":ai_result,"ending":null,"events":[]}))
	invasion_file.close()
	check(scene.native.load_session(path).is_empty(),"original AI invasion loads through public save API")
	scene.refresh()
	scene.show_battle_details()
	check(scene.deployment_start.visible and scene.battle_defenders.item_count==2 and scene.battle_attackers.item_count==4,"human defense offers deployment with original rosters")
	scene.deployment_start.emit_signal("pressed")
	check(scene.state.battle.deployment.side=="defender" and int(scene.state.sram[0xdab])==0x86 and int(scene.state.sram[0xdc3])==255,"defender goes first while AI attackers remain undeployed")
	check(int(scene.state.rulers[3].books)==0 and scene.state.battle.deployment_area[0x85] and not scene.state.battle.deployment_area[0x87],"defense applies original order cleanup and legal area")
	scene.deployment_arrows[0].emit_signal("pressed")
	check(int(scene.state.sram[0xdab])==0x85 and int(scene.state.sram[0xe9f])==0x10,"defender movement writes native occupancy")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and int(scene.native.session_snapshot().sram[0xdab])==0x85,"active human defense saves and resumes")
	scene.deployment_confirm.emit_signal("pressed")
	check(int(scene.state.battle.deployment.current)==1 and int(scene.state.sram[0xdad])==0x86 and int(scene.state.sram[0xdc3])==255,"next defender appears while AI continues waiting")
	scene.deployment_confirm.emit_signal("pressed")
	check(int(scene.state.battle.deployment.current)==-1 and int(scene.state.sram[0xdc3])==0x7c and int(scene.state.sram[0xdc4])==152,"final defender triggers original automatic attacker deployment")
	check(scene.deployment_confirm.disabled and scene.end_button.disabled and scene.battle_description.text.contains("双方部队"),"completed human defense keeps combat boundary explicit")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and int(scene.native.session_snapshot().battle.deployment.current)==-1,"completed human defense survives save/load")
	scene.battle_details.hide()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	for swapped in [false,true]:
		var pvp_raw=FileAccess.get_file_as_bytes("res://reference/fixtures/expedition-2-before.bin")
		pvp_raw[0xd89]=130 if swapped else 132
		pvp_raw[0xd8a]=132 if swapped else 130
		var pvp_file=FileAccess.open(path,FileAccess.WRITE)
		pvp_file.store_string(JSON.stringify({"format":"native-original-v1","rom_crc32":2966394227,"sram":Array(pvp_raw),"frame_counter":0,"random_cursor":0,"pending_development":null,"pending_search":null}))
		pvp_file.close()
		check(scene.native.load_session(path).is_empty(),"two-player expedition command fixture loads")
		check(not scene.native.dispatch_expedition(13,12,[143,144,145],143).has("error"),"player can attack other human faction")
		scene.refresh()
		scene.show_battle_details()
		var books_before:int=int(scene.state.rulers[4].books)
		scene.deployment_start.emit_signal("pressed")
		check(scene.state.battle.deployment.two_players and scene.state.battle.deployment.side=="defender" and int(scene.state.sram[0xdab])==0x29,"PvP starts with manually deployed defender")
		check(scene.battle_description.text.contains("玩家1" if swapped else "玩家2") and scene.battle_description.text.contains("曹操"),"UI identifies defending player for both controller assignments")
		check(int(scene.state.rulers[4].books)==books_before and int(scene.state.sram[0xdc3])==255,"PvP preserves attacker orders and waits to place attackers")
		scene.deployment_arrows[0].emit_signal("pressed")
		check(int(scene.state.sram[0xdab])==0x28,"PvP defender moves in defender region")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"PvP defender movement saves and resumes")
		for unit in range(4):scene.deployment_confirm.emit_signal("pressed")
		check(scene.state.battle.deployment.handover and int(scene.state.battle.deployment.current)==-1 and scene.deployment_start.visible and scene.deployment_confirm.disabled,"last defender enters explicit handover")
		check(scene.battle_description.text.contains("玩家2" if swapped else "玩家1") and scene.battle_description.text.contains("刘备"),"handover identifies attacking player")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"handover itself saves and resumes")
		scene.battle_details.hide()
		scene.refresh()
		scene.show_battle_details()
		check(scene.deployment_start.visible and scene.deployment_start.text=="进攻方接手布阵" and int(scene.state.sram[0xdc3])==255,"reopened handover waits for explicit acceptance")
		var handover_key=InputEventKey.new()
		handover_key.keycode=KEY_ENTER
		handover_key.pressed=true
		scene.battle_details.emit_signal("window_input",handover_key)
		check(not scene.state.battle.deployment.handover and int(scene.state.battle.deployment.current)==0 and int(scene.state.sram[0xdc3])==0x2f,"Enter accepts handover and starts first attacker")
		scene.deployment_arrows[0].emit_signal("pressed")
		check(int(scene.state.sram[0xdc3])==0x2e,"PvP attacker moves in attacker region")
		for unit in range(3):scene.deployment_confirm.emit_signal("pressed")
		check(int(scene.state.battle.deployment.current)==-1 and not scene.deployment_start.visible and scene.deployment_confirm.disabled and scene.end_button.disabled,"both humans finish deployment at combat boundary")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"completed PvP placements survive save/load")
		scene.battle_details.hide()
		DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	scene.show_battle_details()
	check(scene.tactical_start.visible,"completed human deployment offers tactical movement")
	var deployment_sram:Array=scene.state.sram.duplicate()
	scene.tactical_start.emit_signal("pressed")
	check(scene.state.battle.has("tactics") and int(scene.state.battle.tactics.points)==20 and scene.state.sram==deployment_sram,"tactical entry grants original shared mobility without SRAM changes")
	check(not scene.tactical_start.visible and not scene.deployment_confirm.visible and not scene.deployment_arrows[0].disabled,"tactical controls replace deployment confirmation")
	scene.deployment_arrows[0].emit_signal("pressed")
	check(int(scene.state.sram[0xdc3])==0x2d and int(scene.state.battle.tactics.points)<20,"tactical movement updates position and spends mobility")
	var points_before:int=int(scene.state.battle.tactics.points)
	scene.battle_attackers.emit_signal("item_selected",1)
	check(int(scene.state.battle.tactics.selected)==1 and int(scene.state.battle.tactics.points)==points_before,"selecting another attacker preserves shared mobility")
	scene.deployment_arrows[0].emit_signal("pressed")
	check(int(scene.state.sram[0xdc6])==0x2e and int(scene.state.battle.tactics.points)<points_before,"second attacker uses same mobility budget")
	var tactical_sram:Array=scene.state.sram.duplicate()
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().sram==tactical_sram,"tactical movement and selected officer replay on load")
	scene.battle_details.hide()
	scene.refresh()
	scene.show_battle_details()
	check(int(scene.state.battle.tactics.selected)==1 and not scene.deployment_confirm.visible and not scene.tactical_start.visible,"reopened tactical window preserves selection and stage")
	check(scene.end_button.disabled and scene.tactical_end.visible,"tactical handover uses its own control without skipping the strategic battle")
	scene.battle_details.hide()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	# Fresh valid expedition: deploy closer before starting the first tactical turn.
	var attack_raw=FileAccess.get_file_as_bytes("res://reference/fixtures/expedition-2-before.bin")
	var attack_file=FileAccess.open(path,FileAccess.WRITE)
	attack_file.store_string(JSON.stringify({"format":"native-original-v1","rom_crc32":2966394227,"sram":Array(attack_raw),"frame_counter":0,"random_cursor":0,"pending_development":null,"pending_search":null}))
	attack_file.close()
	check(scene.native.load_session(path).is_empty() and not scene.native.dispatch_expedition(13,12,[143,144,145],143).has("error"),"attack UI starts from valid original expedition")
	check(scene.native.prepare_deployment().is_empty(),"attack UI prepares original battlefield")
	for step in range(2):scene.native.move_deployment(2)
	for step in range(16):
		if not scene.native.move_deployment(1).is_empty():break
	for unit in range(3):scene.native.confirm_deployment()
	scene.refresh()
	scene.show_battle_details()
	scene.tactical_start.emit_signal("pressed")
	check(scene.attack_controls.visible and scene.attack_arrows.size()==4 and not scene.attack_confirm.visible,"four attack directions appear in tactical controls")
	var support_points:int=int(scene.state.battle.tactics.points)
	var formation_offset:int=0x438+int(scene.state.sram[0xdc2])*8+4
	var formation_before:int=int(scene.state.sram[formation_offset])
	scene.formation_next.emit_signal("pressed")
	check(int(scene.state.sram[formation_offset])==((formation_before&252)|mini(3,(formation_before&3)+1)) and int(scene.state.battle.tactics.points)==support_points,"formation arrows preserve troop bits and cost no mobility")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"formation change survives public save/load")
	scene.scout_button.emit_signal("pressed")
	check(scene.state.battle.tactics.has("scout") and int(scene.state.battle.tactics.points)==support_points-1 and scene.scout_close.visible,"scout button charges one point and opens enemy report")
	check(scene.deployment_arrows[0].disabled and not scene.attack_controls.visible and scene.battle_description.text.contains("智力"),"scouting report displays original stats and pauses commands")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"open scouting report survives save/load")
	scene.battle_details.hide()
	scene.refresh()
	scene.show_battle_details()
	check(scene.scout_close.visible and int(scene.state.battle.tactics.points)==support_points-1,"reopening scouting report does not charge again")
	scene.scout_close.emit_signal("pressed")
	check(not scene.state.battle.tactics.has("scout") and int(scene.state.battle.tactics.points)==support_points-1 and scene.attack_controls.visible,"close scout report returns tactical controls without refund")
	var no_enemy:Array=scene.state.sram.duplicate()
	var no_enemy_points:int=int(scene.state.battle.tactics.points)
	scene.attack_arrows[0].emit_signal("pressed")
	check(scene.state.sram==no_enemy and int(scene.state.battle.tactics.points)==no_enemy_points and not scene.state.battle.tactics.has("attack"),"empty attack direction costs nothing")
	# Stay on the current row and approach the defender, stopping before occupancy.
	var reached_enemy:bool=false
	for step in range(16):
		scene.attack_arrows[1].emit_signal("pressed")
		if scene.state.battle.tactics.has("attack"):
			reached_enemy=true
			break
		scene.deployment_action("1")
	check(reached_enemy,"UI movement reaches adjacent enemy and starts attack")
	if reached_enemy:
		var attack_points:int=int(scene.state.battle.tactics.points)
		check(scene.attack_confirm.visible and scene.attack_cancel.visible and scene.deployment_arrows[0].disabled,"pending attack locks movement and offers confirmation or cancellation")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"pending attack survives public Godot save/load")
		scene.attack_cancel.emit_signal("pressed")
		check(not scene.state.battle.tactics.has("attack") and int(scene.state.battle.tactics.points)==attack_points,"cancel attack preserves spent mobility")
		check(scene.native.load_session(path).is_empty(),"resume pending attack without another payment")
		scene.refresh()
		scene.show_battle_details()
		scene.native.tick(7)
		scene.attack_confirm.emit_signal("pressed")
		check(scene.state.battle.tactics.attack.stage=="clash_ready" and not scene.attack_confirm.visible and not scene.attack_cancel.visible,"confirmation reaches persisted clash preparation boundary")
		var clash_sram:Array=scene.state.sram.duplicate()
		var clash:Dictionary=scene.state.battle.tactics.attack.duplicate(true)
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().sram==clash_sram and scene.native.session_snapshot().battle.tactics.attack==clash,"NPC formation and terrain sides replay exactly")
		scene.battle_details.hide()
		scene.refresh()
		scene.show_battle_details()
		check(scene.state.battle.tactics.attack==clash and scene.state.battle.tactics.attack.stage=="clash_ready" and scene.end_button.disabled and scene.deployment_arrows[0].disabled,"reopened clash preserves pending preparation and blocks strategic actions")
		check(scene.clash_start.visible and not scene.clash_controls.visible,"prepared clash offers native army screen")
		scene.clash_start.emit_signal("pressed")
		check(scene.state.battle.tactics.attack.stage=="clash_orders" and scene.clash_controls.visible and not scene.battle_overlay.visible,"native clash board replaces tactical overlay")
		var live:Dictionary=scene.state.battle.tactics.attack.clash.duplicate(true)
		var human:int=1 if int(live.players[0])==0 else 0
		check(scene.clash_orders.size()==8 and scene.clash_orders[(human^1)*4].disabled and not scene.clash_orders[human*4].disabled,"human controller alone can change army orders")
		var image:Image=scene.native.clash_image()
		check(image.get_width()==256 and image.get_height()==160 and live.runtime.units.size()==66,"original scene and 22 native unit records reach Godot")
		var clash_points_before:int=int(scene.state.battle.tactics.points)
		for kind in range(4):scene.clash_orders[human*4+kind].emit_signal("pressed")
		check(scene.state.battle.tactics.attack.clash.runtime.orders[human*4]==1.0 and int(scene.state.battle.tactics.points)==clash_points_before,"order buttons update C++ without spending tactical mobility")
		var entered:Dictionary=scene.state.battle.tactics.attack.duplicate(true)
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().battle.tactics.attack==entered,"army positions and edited orders survive public save/load")
		scene.refresh()
		scene.show_battle_details()
		check(scene.clash_controls.visible and scene.battle_texture.texture.get_image().get_data()==image.get_data() and scene.battle_description.text.contains("可逐步或自动推进交锋"),"reopening preserves original board and reports the current playable boundary")
		await process_frame
		if DisplayServer.get_name()!="headless":root.get_texture().get_image().save_png("res://clash-armies-preview.png")
		var fighting_path="user://native-clash-running-test.json"
		# This fixture is checked against legal C++ deployment/movement/attack replay.
		check(scene.native.load_session("res://tests/clash-session-start.json").is_empty(),"original terrain opens player-first execution fixture")
		scene.refresh()
		scene.show_battle_details()
		var execution_points:int=int(scene.state.battle.tactics.points)
		check(scene.clash_step.visible and scene.clash_auto.visible,"army UI exposes single-step and automatic execution")
		scene.clash_auto.emit_signal("pressed")
		check(not scene.clash_timer.is_stopped(),"automatic timer starts explicitly")
		await scene.clash_timer.timeout
		check(scene.state.battle.tactics.attack.stage=="clash_running","timer advances the native execution boundary")
		scene.battle_details.hide()
		check(scene.clash_timer.is_stopped(),"closing the battle pauses the timer")
		scene.show_battle_details()
		var before_fighting:Array=scene.state.battle.tactics.attack.clash.runtime.units.duplicate()
		for step in range(340):
			if scene.state.battle.tactics.attack.stage not in ["clash_orders","clash_running"]:break
			scene.clash_step.emit_signal("pressed")
			if step==70 and DisplayServer.get_name()!="headless":
				await process_frame
				root.get_texture().get_image().save_png("res://clash-execution-preview.png")
			if step==12:
				var running:Dictionary=scene.state.battle.tactics.attack.duplicate(true)
				check(scene.native.save_session(fighting_path).is_empty() and scene.native.load_session(fighting_path).is_empty() and scene.native.session_snapshot().battle.tactics.attack==running,"public bindings restore mid-action execution")
		var fighting:Dictionary=scene.state.battle.tactics.attack.duplicate(true)
		check(fighting.clash.runtime.units!=before_fighting and int(scene.state.battle.tactics.points)==execution_points,"native execution updates armies without charging tactical points")
		check(scene.native.save_session(fighting_path).is_empty() and scene.native.load_session(fighting_path).is_empty() and scene.native.session_snapshot().battle.tactics.attack==fighting,"execution end boundary remains saveable")
		if fighting.stage=="clash_running":
			scene.clash_auto.emit_signal("pressed")
			check(not scene.clash_timer.is_stopped(),"automatic advance starts explicitly")
			scene.battle_details.hide()
			check(scene.clash_timer.is_stopped(),"closing battle pauses automatic execution")
			scene.show_battle_details()
		else:check(not scene.clash_step.visible and scene.clash_timer.is_stopped(),"unimplemented flow or surrender pauses automatic execution")
		await process_frame
		if DisplayServer.get_name()!="headless":root.get_texture().get_image().save_png("res://clash-execution-result-preview.png")
		check(scene.native.load_session(path).is_empty(),"return to independently saved army orders")
		scene.refresh()
		scene.show_battle_details()
		DirAccess.remove_absolute(ProjectSettings.globalize_path(fighting_path))
		check(scene.surrender_submit.visible and scene.surrender_submit.disabled,"surrender submission requires the matching general order")
		scene.clash_orders[human*4+3].emit_signal("pressed")
		scene.clash_orders[human*4+3].emit_signal("pressed")
		check(not scene.surrender_submit.disabled,"ordinary general can select surrender")
		var before_surrender:Array=scene.state.sram.duplicate()
		scene.surrender_submit.emit_signal("pressed")
		check(scene.surrender_yes.visible and scene.surrender_no.visible and scene.clash_orders[human*4].disabled,"surrender confirmation locks army editing")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"surrender confirmation saves and reloads")
		scene.surrender_no.emit_signal("pressed")
		check(scene.state.battle.tactics.attack.stage=="clash_orders" and scene.state.sram==before_surrender,"cancelling surrender preserves armies and returns to orders")
		scene.surrender_submit.emit_signal("pressed")
		scene.surrender_yes.emit_signal("pressed")
		check(scene.state.battle.tactics.attack.stage=="surrender_notice" and scene.surrender_next.visible and not scene.surrender_no.visible,"accepted surrender enters the announcement")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"announcement saves and reloads")
		scene.surrender_next.emit_signal("pressed")
		check(scene.state.battle.tactics.attack.stage=="surrender_accepted" and scene.state.sram==before_surrender,"opponent acceptance still waits before settlement")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"opponent acceptance saves and reloads")
		scene.surrender_next.emit_signal("pressed")
		check(scene.state.battle.tactics.attack.stage=="clash_result" and scene.clash_result_close.visible and not scene.clash_controls.visible,"settlement shows the restored tactical board")
		var captured_officer:int=int(live.first if human==0 else live.second)
		check(scene.state.battle.tactics.captives.has(float(captured_officer)) and int(scene.state.sram[0xdc2])==255 and int(scene.state.battle.tactics.points)==clash_points_before,"capture ledger and original mobility survive surrender")
		var final_surrender:Dictionary=scene.state.battle.tactics.duplicate(true)
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().battle.tactics==final_surrender,"settled result saves without applying loyalty or capture twice")
		await process_frame
		if DisplayServer.get_name()!="headless":root.get_texture().get_image().save_png("res://clash-surrender-preview.png")
		scene.clash_result_close.emit_signal("pressed")
		check(not scene.state.battle.tactics.has("attack") and scene.battle_description.text.contains("战斗俘虏：1"),"surviving armies resume tactics with visible captive status")
		check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"resumed tactical state preserves prisoners")
	scene.battle_details.hide()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	for variant in [0,2,5,6]:
		check(scene.native.load_session("res://tests/clash-retreat-%d.json" % variant).is_empty(),"load controlled clash retreat boundary %d" % variant)
		scene.refresh()
		scene.show_battle_details()
		check(scene.clash_retreat_next.visible and scene.clash_retreat_row.visible and not scene.surrender_identity.visible and scene.battle_description.text.contains("撤离边界"),"legacy retreat entry exposes its continuation and correct general")
		var retreat_points_before:int=int(scene.state.battle.tactics.points)
		for step in range(5):
			if scene.state.battle.tactics.attack.stage=="clash_result":break
			scene.clash_retreat_next.emit_signal("pressed")
			var progress:Dictionary=scene.state.battle.tactics.attack.duplicate(true)
			check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().battle.tactics.attack==progress,"pursuit, desertion and retreat result stages save exactly")
			if variant==2 and progress.stage=="clash_retreat" and int(progress.clash.runtime.counter)==6:
				check(scene.battle_description.text.contains("1 支兵队离散") and not scene.clash_step.visible,"desertion message reports original losses and holds execution")
				await process_frame
				if DisplayServer.get_name()!="headless":root.get_texture().get_image().save_png("res://clash-retreat-loss-preview.png")
		var result:Dictionary=scene.state.battle.tactics.attack.result
		check(result.kind=="retreat" and scene.clash_result_close.visible and not scene.clash_retreat_next.visible and int(scene.state.battle.tactics.points)==retreat_points_before,"clash retreat result preserves mobility and closes its acknowledgements")
		if variant==5:
			check(int(result.phase)==15 and scene.state.battle.human_failure_available and not scene.clash_result_close.disabled and not scene.battle_overlay.visible and scene.battle_description.text.contains("君主战败"),"ruler defeat keeps original phase and battlefield without granting continuation")
			await process_frame
			if DisplayServer.get_name()!="headless":root.get_texture().get_image().save_png("res://clash-retreat-ruler-preview.png")
		else:
			check(result.map_restored and scene.battle_overlay.visible and not scene.clash_result_close.disabled,"ordinary clash retreat restores tactical board")
			scene.clash_result_close.emit_signal("pressed")
			check(not scene.state.battle.tactics.has("attack") and scene.state.battle.tactics.last_clash.kind=="retreat","return from clash retreat to remaining tactical actions")
		scene.battle_details.hide()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	for variant in range(4):
		check(scene.native.load_session("res://tests/clash-defeat-%d.json" % variant).is_empty(),"load direct general defeat entry %d" % variant)
		scene.refresh()
		scene.show_battle_details()
		var defeat_points_before:int=int(scene.state.battle.tactics.points)
		check(scene.clash_defeat_row.visible and scene.clash_defeat_next.visible and not scene.clash_retreat_row.visible and not scene.surrender_identity.visible and not scene.clash_step.visible,"defeat entry exposes correct identity and holds automatic execution")
		for step in range(2):
			scene.clash_defeat_next.emit_signal("pressed")
			var progress:Dictionary=scene.state.battle.tactics.duplicate(true)
			check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty() and scene.native.session_snapshot().battle.tactics==progress,"defeat announcement and result save exactly")
			if step==0:
				check(progress.attack.stage=="clash_defeat" and int(progress.attack.clash.runtime.counter)==2 and scene.battle_description.text.contains("武将败北已登记") and scene.clash_defeat_next.visible,"original defeat announcement awaits acknowledgement")
				await process_frame
				if variant==0 and DisplayServer.get_name()!="headless":root.get_texture().get_image().save_png("res://clash-defeat-announcement-preview.png")
		var result:Dictionary=scene.state.battle.tactics.attack.result
		check(result.kind=="defeat" and not scene.clash_defeat_next.visible and not scene.surrender_identity.visible and int(scene.state.battle.tactics.points)==defeat_points_before,"defeat result preserves mobility without mislabeling surrender")
		if variant==2:
			check(scene.state.battle.commander_defeat_result_available and not scene.clash_result_close.disabled and scene.clash_result_close.text.contains("主将离场"),"commander defeat offers original reason 20 settlement")
		elif variant==3:
			check(scene.state.battle.human_failure_available and not scene.clash_result_close.disabled and scene.battle_description.text.contains("君主战败"),"ruler defeat exposes the separate human failure report")
		else:
			check(result.map_restored and scene.battle_overlay.visible and not scene.clash_result_close.disabled,"ordinary defeated general leaves and tactical map returns")
			scene.clash_result_close.emit_signal("pressed")
			check(not scene.state.battle.tactics.has("attack") and scene.state.battle.tactics.last_clash.kind=="defeat","remaining armies resume tactics after general defeat")
		if variant==3:
			check(int(result.phase)==15 and not scene.battle_overlay.visible and scene.battle_description.text.contains("君主战败"),"human ruler defeat retains original global phase and clash picture")
			await process_frame
			if DisplayServer.get_name()!="headless":root.get_texture().get_image().save_png("res://clash-defeat-ruler-preview.png")
		scene.battle_details.hide()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	# Complete voluntary attacker retreat must actually return to strategic play.
	var retreat_file=FileAccess.open(path,FileAccess.WRITE)
	retreat_file.store_string(JSON.stringify({"format":"native-original-v1","rom_crc32":2966394227,"sram":Array(attack_raw),"frame_counter":0,"random_cursor":0,"pending_development":null,"pending_search":null}))
	retreat_file.close()
	check(scene.native.load_session(path).is_empty(),"retreat command fixture loads")
	check(not scene.native.dispatch_expedition(13,12,[143,144,145],143).has("error") and scene.native.prepare_deployment().is_empty(),"retreat integration dispatches actual residents")
	for unit in range(3):scene.native.confirm_deployment()
	scene.native.begin_tactics()
	scene.refresh()
	scene.show_battle_details()
	var retreat_points:int=int(scene.state.battle.tactics.points)
	scene.retreat_button.emit_signal("pressed")
	check(scene.retreat_confirm.visible and scene.retreat_cancel.visible and not scene.attack_controls.visible,"ordinary retreat opens explicit confirmation")
	scene.retreat_cancel.emit_signal("pressed")
	check(not scene.state.battle.tactics.has("retreat") and int(scene.state.battle.tactics.points)==retreat_points,"cancel retreat before confirmation is free")
	scene.retreat_button.emit_signal("pressed")
	scene.retreat_confirm.emit_signal("pressed")
	check(int(scene.state.sram[0xdc2])==255 and int(scene.state.battle.tactics.points)==retreat_points-1 and scene.retreat_finish.visible,"ordinary unit returns home and charges one mobility")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"retreat result with removed unit survives public save/load")
	scene.retreat_finish.emit_signal("pressed")
	check(scene.state.phase=="expedition" and not scene.state.battle.tactics.has("retreat"),"ordinary retreat keeps remaining army in battle")
	check(scene.native.select_tactical_unit(2).is_empty(),"select commander for army withdrawal")
	scene.refresh()
	scene.show_battle_details()
	scene.retreat_button.emit_signal("pressed")
	check(scene.battle_description.text.contains("全部进攻部队"),"commander retreat warns about the whole army")
	scene.retreat_confirm.emit_signal("pressed")
	check(scene.state.battle.tactics.retreat.ended and scene.battle_attackers.item_count==1,"commander withdrawal empties attacker ledger")
	check(scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"complete army withdrawal waits in resumable result phase")
	scene.retreat_finish.emit_signal("pressed")
	check(scene.state.phase=="player_commands" and scene.state.battle==null and not scene.battle_details.visible and int(scene.state.sram[12*36+32])==255,"result confirmation clears battle flags and returns to strategy")
	check(scene.state.cities[13].officer_slots.count(null)==8 and scene.native.save_session(path).is_empty() and scene.native.load_session(path).is_empty(),"all expedition officers returned and strategic save reloads")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	scene.queue_free()
	await process_frame
	print("ORIGINAL CAMPAIGN: %d failures" % failures)
	await root.get_node("OriginalSound").shutdown()
	quit(1 if failures else 0)
